[package]
name = "bridge-relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
env_logger = "0.10"
codec = { package = "parity-scale-codec", version = "3.0" }

# Substrate dependencies
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }

# Bridge dependencies
relay-substrate-client = { git = "https://github.com/paritytech/parity-bridges-common.git" }
relay-utils = { git = "https://github.com/paritytech/parity-bridges-common.git" }
bp-messages = { git = "https://github.com/paritytech/parity-bridges-common.git" }
bp-runtime = { git = "https://github.com/paritytech/parity-bridges-common.git" }